### ISSUE TITLE
Version tags?

### ISSUE THREAD

**Issue by zakdances** [ReactiveCocoa/ReactiveCocoaIO#3]
Would adding some version tags be a good idea? It'd certainly help forkers keep track of main branch progress. Versioning would also help CocoaPods users tag the requirement in their podfiles.

**Comment by Coneko** [comment]
Sorry it's still a proof of concept so to say, so there's not much to tag.

**Comment by zakdances** [comment]
Looks like the first commit was made [about 8 months ago](https://github.com/ReactiveCocoa/ReactiveCocoaIO/commit/e87490e152abce5f41adfa70e8a3b15e75d7f308). Do you have an informal roadmap in mind for this project? A rough ETA on when you think an alpha would be appropriate?

**Comment by Coneko** [comment]
No idea. I made this for a personal project and since it did what I needed it to do I haven't touched it since.

I updated it to use the latest version of ReactiveCocoa so you can go ahead use it if you feel adventurous.

**Comment by zakdances** [comment]
Thank you. 

Question: According to the latest [RC changelog](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/CHANGELOG.md) `RACPropertySubject` should be replaced with `RACChannel`. Yet in most instances, you replace it with `RACChannelTerminal`. I'm currently learning RCv2 and I'd love to know your thinking behind that. Why the deviation from the guidelines?

**Comment by Coneko** [comment]
`RACChannel` is indeed the more natural replacement, but if you look at the RAC APIs the binding methods return `RACChannelTerminal`s even when the methods refer to channels (`RACChannelTo()` and `-rac_channelToBinding:` for example) because exposing the `RACChannel` itself is clunky and might expose implementation details.

In hindsight I should have exposed a `RACBinding` and kept the `RACPropertySubject` as an implementation detail in the old version as well.

If you aren't familiar with `RACPropertySubject` and `RACBinding` I suggest you don't bother with them at all, `RACChannel` is a really big improvement over them.
